apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-apache 
  labels:
    app: php-apache 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-apache 
  template:
    metadata:
      labels:
        app: php-apache 
        #role: hello
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"